-- docs/sql/scrum-340-la-plaza-comprada.sql — SCRUM-340
--
-- LA SEÑAL DURADERA DE «COMPRÓ PLAZA DE FUNDADOR». Una columna. **Nada más.**
--
-- ESTADO (8-sep-2026):
--    · desarrollo, staging y producción → ⛔ TODAS pendientes. Las aplica el fundador.
--    · esta sesión NO ha ejecutado nada contra ninguna base. Ni con `--dry-run`.
--
-- ─────────────────────────────────────────────────────────────────────────────────────────
-- POR QUÉ HACE FALTA, Y POR QUÉ NINGUNA COLUMNA EXISTENTE SIRVE
--
-- Decisión del fundador (8-sep-2026), literal:
--
--   «la plaza se queda con él; si se retrasa en un pago tiene un tiempo para pagarla, y si no,
--    esa plaza desaparece con el merchant».
--
-- O sea: **cancelar NO libera la plaza. `past_due` NO libera la plaza.** La plaza sólo desaparece
-- cuando desaparece el merchant. Ninguna de las columnas de hoy puede expresar eso:
--
--   · `plan`                        → vuelve a `'trial'` al cancelar (`stripe.routes.ts:138,151`),
--                                     así que LIBERA la plaza. Es el criterio de `main` hoy.
--   · `subscriptionStatus`          → dice SI paga, no QUÉ compró. Y el webhook escribe `'active'`
--                                     para `pro` y para `founding` por igual (`:77`), así que
--                                     contar por él hace que **cada suscriptor PRO activo ocupe
--                                     una plaza de fundador** — medido el 8-sep-2026.
--   · `lifecycleEmailsSent.firstPayment` → acredita que hubo un primer cobro, pero **no dice de
--                                     qué plan**. Mismo defecto que el anterior.
--
-- 🔒 LO QUE ESTA COLUMNA REPARA no es un contador: es un SIGNIFICADO. El guard de SCRUM-330
-- defendía que «el estado de la suscripción NO se deduce del plan: son DOS columnas». Con esto las
-- dos columnas existen de verdad y son independientes:
--
--      founding_purchased_at  →  QUÉ compró   (y no se borra nunca)
--      subscription_status    →  SI está pagando
--
-- ─────────────────────────────────────────────────────────────────────────────────────────
-- 🔴 NULLABLE Y SIN DEFAULT, A PROPÓSITO
--
-- `NULL` = «no consta que comprara plaza de fundador», que es la verdad de todas las filas de hoy.
-- Un `DEFAULT` convertiría a TODOS los merchants históricos en fundadores de golpe, y eso no lo ha
-- dicho nadie. Es el mismo criterio que `Invoice.suplidos` (SCRUM-500) y `Merchant.paidVia`
-- (SCRUM-441): sin default, para que «no consta» no se confunda con un valor.
--
-- RELLENO INICIAL: **NULL para todas las filas**, y está justificado con una medición, no con una
-- suposición: **nadie ha comprado jamás plaza de fundador** (SCRUM-41 abierto, cero clientes de
-- pago). La landing dirá «20 de 20» y será CIERTO.
--   ⚠️ Antes de aplicar esto, córrase `docs/sql/scrum-340-verificar.sql`. Si alguna fila
--      contradice lo anterior, **NO se aplica**: se para y se decide el backfill.
--
-- ─────────────────────────────────────────────────────────────────────────────────────────
-- ⛔ SIN ÍNDICE, y es deliberado
--
-- La oferta son 20 plazas y la tabla `merchants` es pequeña; un índice sobre una columna casi toda
-- a `NULL` no paga su coste de escritura. Si algún día la tabla crece, se añade entonces — con la
-- medición delante, no antes.
--
-- ⛔ SIN CLAVE AJENA: no apunta a nada. Es un sello temporal.
--
-- ─────────────────────────────────────────────────────────────────────────────────────────
-- ADITIVA Y REVERSIBLE: `ADD COLUMN` nullable no toca ni una fila existente, y se deshace con un
-- `DROP COLUMN` limpio. Nada de lo que hay hoy deja de funcionar al aplicarla: el contador actual
-- no la lee (todavía), así que aplicar esto NO cambia el número que pinta la landing.
--
-- 🔴 ESTE FICHERO ES SÓLO DDL. La comprobación vive aparte, en
-- `docs/sql/scrum-340-verificar.sql`: el clasificador del aplicador rechaza un `SELECT` dentro de
-- un fichero de DDL (lección de SCRUM-650), y mezclarlos deja el ALTER sin poder ejecutarse.
-- ─────────────────────────────────────────────────────────────────────────────────────────

ALTER TABLE merchants ADD COLUMN IF NOT EXISTS founding_purchased_at TIMESTAMP(3);
